[package]
name = "adder"
version = "0.1.0"
edition = "2021"

# opt-level range 0-3 == number of optimisations
[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
